---
name: YAML Lint

on:
  pull_request:
    paths:
      - '**/*.yml'
      - '**/*.yaml'
  push:
    branches: [main]
    paths:
      - '**/*.yml'
      - '**/*.yaml'

jobs:
  yaml-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install yamllint
        run: pip install yamllint

      - name: Lint YAML files
        run: |
          yamllint -c .yamllint.yml .
